apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-dev
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-dev
  namespace: rabbitmq-dev
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
    additionalConfig: |
      default_user=admin
      default_pass=shivang
  persistence:
    storageClassName: default
    storage: "30Gi"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  service:
    type: ClusterIP