apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vhosts.rabbitmq.com
spec:
  group: rabbitmq.com
  versions:
    - name: v1beta1
      served: true  
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rabbitmqClusterReference:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
              
            status:
              type: object
              properties:
                # status props
                
  scope: Namespaced  
  names:
    plural: vhosts
    singular: vhost
    kind: Vhost
    shortNames:
      - vhost