apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vhosts.rabbitmq.com
spec:
  group: rabbitmq.com
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object 
              properties:
                name:
                  type: string
                namespace:
                  type: string
            
            spec:
              type: object
              properties:
                name:
                  type: string
                rabbitmqClusterReference:
                  type: object
                  properties:
                    name:
                      type: string
            
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                      lastTransitionTime:
                        type: string
                        
  scope: Namespaced
  names:
    plural: vhosts
    singular: vhost
    kind: Vhost
    shortNames:
      - vhost
